/**
 * Status codes for Chatbot API
 */
export enum StatusCode {
    SUCCESS="SUCCESS",
    INVALID_API_KEY="INVALID_API_KEY",
    MISSING_REQUIRED_PARAMETERS="MISSING_REQUIRED_PARAMETERS",
    USER_NOT_FOUND="USER_NOT_FOUND",
    MESSAGE_NOT_FOUND="MESSAGE_NOT_FOUND",
    BAD_REQUEST="BAD_REQUEST",
    INTERNAL_SERVER_ERROR="INTERNAL_SERVER_ERROR"
  }
  